<?php
/**
 * @file
 * This is the file description for Link Onclick module.
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly. Make sure to wrap your documentation in column 78 so
 * that the file can be displayed nicely in default-sized consoles.
 */

/**
 * Implements hook_menu().
 */
function link_onclick_init(){
// $js_vars = array('link_onclick' => array('handler' => '#block-views-bloque_los_mas_vistos-block a, a');

  $js_vars = array('link_onclick' => array('handler' => 'a.nid',));
  drupal_add_js($js_vars, 'setting');
  drupal_add_js(drupal_get_path('module', 'link_onclick') . '/link_onclick.js');
}

/**
 * Implements hook_menu().
 */
/*function link_onclick_menu() {
  $items = array();

  // Type '$item ⇥' to create a new menu item.

  return $items;
}*/